"""Home-organization discovery for OpenID Federation RPs and OpenID Connect
Core section 4 Third-Party Initiated Login."""

from typing import Any, Mapping

from pygrindvakt.federation import CollectionEntity, ResolvedEntity
from pygrindvakt.http import HttpClientProtocol

class ThirdPartyInitiatedLogin:
    def __init__(self, iss: str, *, login_hint: str | None = ..., target_link_uri: str | None = ...) -> None: ...
    @property
    def iss(self) -> str: ...
    @property
    def login_hint(self) -> str | None: ...
    @property
    def target_link_uri(self) -> str | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class SelfPublishedRp:
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def exp(self) -> int | None: ...

def validate_entity_id(s: str) -> None: ...
def discovery_request_url(
    discovery_endpoint: str,
    rp_entity_id: str,
    op_hint: str | None = ...,
    target_link_uri: str | None = ...,
) -> str: ...
def parse_third_party_initiated_login(params: Mapping[str, str]) -> ThirdPartyInitiatedLogin: ...
def initiate_login_uri(metadata: Mapping[str, Any]) -> str: ...
def initiate_login_uri_from_resolved(entity: ResolvedEntity) -> str: ...
def self_published_rp(http: HttpClientProtocol | None, rp_entity_id: str) -> SelfPublishedRp: ...
def self_published_initiate_login_uri(http: HttpClientProtocol | None, rp_entity_id: str) -> str: ...
def third_party_login_url(
    initiate_login_uri: str,
    op_entity_id: str,
    login_hint: str | None = ...,
    target_link_uri: str | None = ...,
) -> str: ...
def promote_hint(entities: list[CollectionEntity], hint: str) -> tuple[bool, list[CollectionEntity]]: ...
