from typing import Any

from .http import _HttpArg
from .keys import SigningKey

ENTITY_STATEMENT_TYP: str
RESOLVE_RESPONSE_TYP: str
JWK_SET_TYP: str

class EntityStatement:
    @property
    def claims(self) -> dict[str, Any]: ...
    def iss(self) -> str | None: ...
    def sub(self) -> str | None: ...
    def jwks(self) -> dict[str, Any]: ...
    def metadata(self, kind: str) -> dict[str, Any] | None: ...
    def authority_hints(self) -> list[str]: ...

class ResolvedEntity:
    @property
    def issuer(self) -> str: ...
    @property
    def subject(self) -> str: ...
    @property
    def metadata(self) -> dict[str, Any]: ...
    @property
    def subject_jwks(self) -> dict[str, Any]: ...
    @property
    def exp(self) -> int | None: ...

class CollectionEntity:
    def __init__(self, *, entity_id: str, display_name: str, logo_uri: str | None = ...) -> None: ...
    @property
    def entity_id(self) -> str: ...
    @property
    def display_name(self) -> str: ...
    @property
    def logo_uri(self) -> str | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

def build_entity_configuration(
    key: SigningKey,
    entity_id: str,
    public_jwks: dict[str, Any],
    authority_hints: list[str],
    metadata: dict[str, Any],
    trust_marks: list[dict[str, Any]] | None = ...,
    lifetime: int = ...,
) -> str: ...
def decode_unverified(token: str) -> EntityStatement: ...
def verify(token: str, jwks: dict[str, Any]) -> EntityStatement: ...
def verify_typed(token: str, jwks: dict[str, Any], typ: str) -> EntityStatement: ...
def verify_self_signed(token: str) -> EntityStatement: ...
def fetch_entity_configuration(http: _HttpArg, entity_id: str) -> str: ...
def resolve_via_trust_anchors(
    http: _HttpArg, sub: str, trust_anchors: dict[str, dict[str, Any]]
) -> ResolvedEntity: ...
def entity_metadata_jwks(
    http: _HttpArg,
    metadata: dict[str, Any],
    subject_entity_id: str,
    subject_fed_jwks: dict[str, Any],
) -> dict[str, Any]: ...
def fetch_signed_jwks(
    http: _HttpArg,
    signed_jwks_uri: str,
    subject_entity_id: str,
    subject_fed_jwks: dict[str, Any],
) -> dict[str, Any]: ...
def fetch_collection(
    http: _HttpArg, collection_endpoint: str, entity_type: str
) -> list[CollectionEntity]: ...
def parse_collection(body: dict[str, Any], entity_type: str) -> list[CollectionEntity]: ...
def apply_policy(metadata: dict[str, Any], policy: dict[str, Any]) -> dict[str, Any]: ...
