"""Type stubs for ``pygrindvakt.metadata`` - the OpenID Provider discovery
document."""

from typing import Any

class ProviderMetadata:
    """OpenID Provider metadata (the ``/.well-known/openid-configuration`` document).

    ``ProviderMetadata(issuer, base)`` fills in the standard endpoints under
    ``base`` (``/authorization``, ``/token``, ``/userinfo``, ``/jwks``) and
    sensible defaults; every field is settable. Unknown / extension fields
    live in ``extra``.
    """

    def __init__(self, issuer: str, base: str | None = ...) -> None: ...
    @staticmethod
    def from_dict(d: dict[str, Any]) -> ProviderMetadata:
        """Build from a discovery-document dict."""
    def to_dict(self) -> dict[str, Any]:
        """The discovery document as a dict."""
    @property
    def issuer(self) -> str: ...
    @issuer.setter
    def issuer(self, value: str) -> None: ...
    @property
    def authorization_endpoint(self) -> str: ...
    @authorization_endpoint.setter
    def authorization_endpoint(self, value: str) -> None: ...
    @property
    def token_endpoint(self) -> str: ...
    @token_endpoint.setter
    def token_endpoint(self, value: str) -> None: ...
    @property
    def userinfo_endpoint(self) -> str: ...
    @userinfo_endpoint.setter
    def userinfo_endpoint(self, value: str) -> None: ...
    @property
    def jwks_uri(self) -> str: ...
    @jwks_uri.setter
    def jwks_uri(self, value: str) -> None: ...
    @property
    def registration_endpoint(self) -> str | None: ...
    @registration_endpoint.setter
    def registration_endpoint(self, value: str | None) -> None: ...
    @property
    def scopes_supported(self) -> list[str]: ...
    @scopes_supported.setter
    def scopes_supported(self, value: list[str]) -> None: ...
    @property
    def response_types_supported(self) -> list[str]: ...
    @response_types_supported.setter
    def response_types_supported(self, value: list[str]) -> None: ...
    @property
    def response_modes_supported(self) -> list[str]: ...
    @response_modes_supported.setter
    def response_modes_supported(self, value: list[str]) -> None: ...
    @property
    def grant_types_supported(self) -> list[str]: ...
    @grant_types_supported.setter
    def grant_types_supported(self, value: list[str]) -> None: ...
    @property
    def subject_types_supported(self) -> list[str]: ...
    @subject_types_supported.setter
    def subject_types_supported(self, value: list[str]) -> None: ...
    @property
    def id_token_signing_alg_values_supported(self) -> list[str]: ...
    @id_token_signing_alg_values_supported.setter
    def id_token_signing_alg_values_supported(self, value: list[str]) -> None: ...
    @property
    def token_endpoint_auth_methods_supported(self) -> list[str]: ...
    @token_endpoint_auth_methods_supported.setter
    def token_endpoint_auth_methods_supported(self, value: list[str]) -> None: ...
    @property
    def claims_supported(self) -> list[str]: ...
    @claims_supported.setter
    def claims_supported(self, value: list[str]) -> None: ...
    @property
    def code_challenge_methods_supported(self) -> list[str]: ...
    @code_challenge_methods_supported.setter
    def code_challenge_methods_supported(self, value: list[str]) -> None: ...
    @property
    def dpop_signing_alg_values_supported(self) -> list[str]: ...
    @dpop_signing_alg_values_supported.setter
    def dpop_signing_alg_values_supported(self, value: list[str]) -> None: ...
    @property
    def claims_parameter_supported(self) -> bool: ...
    @claims_parameter_supported.setter
    def claims_parameter_supported(self, value: bool) -> None: ...
    @property
    def request_parameter_supported(self) -> bool: ...
    @request_parameter_supported.setter
    def request_parameter_supported(self, value: bool) -> None: ...
    @property
    def extra(self) -> dict[str, Any]:
        """Extension fields (anything not modelled above) as a dict."""
    @extra.setter
    def extra(self, value: dict[str, Any]) -> None: ...
    def set_extra_field(self, key: str, value: Any) -> None:
        """Set one extension field."""
